name: Setup OpenMetadata Test Environment
description: Steps needed to have a coherent test environment

inputs:
  python-version:
    description: Python Version to install
    required: true
  java-version:
    description: Java Version to install
    default: '21'
  npm-version:
    description: NPM Version to install
    default: 'v22.x'
  args:
    description: Arguments to pass to run_local_docker.sh
    required: false
    default: "-m no-ui -d mysql"  # Use "-d postgresql" for postgres and Opensearch
  ingestion_dependency:
    description: Ingestion dependency to pass to run_local_docker.sh
    required: false
    default: "mysql,elasticsearch,sample-data"
  install-server:
    description: Whether to install Java, Node, and the OpenMetadata server
    required: false
    default: "true"

runs:
  using: composite
  steps:
    # ---- Install Ubuntu Dependencies ---------------------------------------------
    - name: Install Ubuntu dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y unixodbc-dev python3-venv librdkafka-dev gcc libsasl2-dev build-essential libssl-dev libffi-dev \
        libevent-dev python3-dev libkrb5-dev tdsodbc && ACCEPT_EULA=Y sudo apt-get -qq install -y msodbcsql18
      shell: bash
    # ------------------------------------------------------------------------------

    # ---- Setup Java --------------------------------------------------------------
    - name: Setup JDK ${{ inputs.java-version }}
      if: ${{ inputs.install-server == 'true' }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
    # ------------------------------------------------------------------------------

    # ---- Setup Node --------------------------------------------------------------
    - name: Use Node.js ${{ inputs.npm-version }}
      if: ${{ inputs.install-server == 'true' }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.npm-version }}

    - name: Install yarn
      if: ${{ inputs.install-server == 'true' }}
      run: npm install -g yarn
      shell: bash
    # ------------------------------------------------------------------------------

    # ---- Setup Python Test Environment -------------------------------------------
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Generate Models
      run: |
        python3 -m venv env
        source env/bin/activate
        sudo make install_antlr_cli
        uv pip install "${{ github.workspace }}/ingestion[dev]"
        make generate
      shell: bash

    - name: Install Python Dependencies
      run: |
        source env/bin/activate
        uv pip install "setuptools<81"
        uv pip install --no-build-isolation "cx_Oracle>=8.3.0,<9"
        uv pip install "${{ github.workspace }}/ingestion[all]"
        uv pip install "${{ github.workspace }}/ingestion[test]"
        uv pip install nox
      shell: bash
    # ------------------------------------------------------------------------------

    # ---- Start OpenMetadata Server and ingest Sample Data ------------------------
    - name: Start Server and Ingest Sample Data
      if: ${{ inputs.install-server == 'true' }}
      uses: nick-fields/retry@v3.0.2
      env:
        INGESTION_DEPENDENCY: ${{ inputs.ingestion_dependency }}
      with:
        timeout_minutes: 60
        max_attempts: 2
        retry_on: error
        command: ./docker/run_local_docker.sh ${{ inputs.args }}
